name: Sync to C repository subfolder

on:
  push:
    branches:
      - main  # 监听B仓库main分支的更改

jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: 检出 B 仓库的代码
      - name: Checkout obsidian repository
        uses: actions/checkout@v3
        
      # Step 2: 克隆 C 仓库到本地
      - name: Clone vitePress repository
        run: |
          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/poppop9/vitePress.git
          cd vitePress
          git checkout main

      # Step 3: 将 B 仓库的内容复制到 C 仓库的子文件夹
      - name: Copy B repository to C repository subfolder
        run: |
          mkdir -p vitePress/src/notes
          rsync -av --exclude='.git' ./* vitePress/src/notes/
          
      # Step 4: 提交并推送更改到 C 仓库
      - name: Commit and Push changes to C repository
        run: |
          cd vitePress
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add src/notes
          git commit -m "Sync from B repository" || echo "No changes to commit"
          git push origin main
